login:
  path: /login
  controller: EDB\AdminBundle\Controller\AuthController::login
  methods: GET

check_form_login:
  path: /login-check
  controller: EDB\AdminBundle\Controller\AuthController::check
  methods: POST

media_preview:
  path: /media/preview
  controller: EDB\AdminBundle\Controller\MediaController::renderPreview
  methods: GET

media_upload:
  path: /media/upload
  controller: EDB\AdminBundle\Controller\MediaController::uploadFile
  methods: POST

media_upload_original_path:
  path: /media/render-original
  controller: EDB\AdminBundle\Controller\MediaController::uploadFileGenerateOriginalPath
  methods: POST

media_modal_list:
  path: /media/list-all
  controller: EDB\AdminBundle\Controller\MediaController::list
  methods: GET

media_insert:
  path: /media/insert-media
  controller: EDB\AdminBundle\Controller\MediaController::insert
  methods: GET
