parameters:
  admin_icon: "%env(CMS_ICON)%"
  admin_path: "%env(ADMIN_PATH)%"
  admin_title: "%env(CMS_TITLE)%"
  google_client_id: "%env(OAUTH_GOOGLE_CLIENT_ID)%"
  google_client_secret: "%env(OAUTH_GOOGLE_CLIENT_SECRET)%"
  media_path: "/media"
  source_prefix: "source"
  cache_prefix: "cache"
  media_class: EDB\AdminBundle\Entity\Media

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $mediaPath: '%media_path%'
      $mediaClass: '%media_class%'
      $sourcePrefix: '%source_prefix%'
      $cachePrefix: '%cache_prefix%'

  EDB\AdminBundle\:
    resource: "../../../src/"
    exclude:
      - "../../../src/DependencyInjection/"
      - "../../../src/Entity/"
      - "../../../src/FormBuilder/"
      - "../../../src/ListBuilder/"
      - "../../../src/Admin/"
      - "../../../src/MenuBuilder/MenuGroup.php"
      - "../../../src/MenuBuilder/MenuItem.php"