parameters:
  edb_admin_path: '%env(EDB_ADMIN_PATH)%'
  edb_media_path: '%env(EDB_MEDIA_PATH)%'
  edb_google_id: '%env(EDB_GOOGLE_CLIENT_ID)%'
  edb_google_secret: '%env(EDB_GOOGLE_CLIENT_SECRET)%'

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $sourcePrefix: '%edb_source_prefix%'
      $cachePrefix: '%edb_cache_prefix%'
      $mediaPath: '%edb_media_path%'
      $mediaClass: '%edb_media_class%'
      $userClass: '%edb_user_class%'
      $googleId: '%edb_google_id%'
      $googleSecret: '%edb_google_secret%'

  EDB\AdminBundle\:
    resource: "../../../src/"
    exclude:
      - "../../../src/DependencyInjection/"
      - "../../../src/Entity/"
      - "../../../src/FormBuilder/"
      - "../../../src/ListBuilder/"
      - "../../../src/Admin/"
      - "../../../src/MenuBuilder/MenuGroup.php"
      - "../../../src/MenuBuilder/MenuItem.php"

  EDB\AdminBundle\Route\Loader:
    tags:
      - { name: routing.loader }
